CREATE SEQUENCE APP_USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE APP_USER (
    ID            NUMBER(19,0)   NOT NULL,
    USERNAME      VARCHAR2(100)  NOT NULL,
    PASSWORD_HASH VARCHAR2(255)  NOT NULL,
    DISPLAY_NAME  VARCHAR2(100)  NOT NULL,
    ROLE          VARCHAR2(50)   DEFAULT 'ROLE_USER' NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_APP_USER PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_USERNAME UNIQUE (USERNAME)
);
