CREATE SEQUENCE PUBLIC_TRAVEL_COORD_HIST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PUBLIC_TRAVEL_COORD_HIST (
    ID                  NUMBER(19,0)    NOT NULL,
    EXTERNAL_CONTENT_ID VARCHAR2(50)    NOT NULL,
    LATITUDE            NUMBER(11,7)    NOT NULL,
    LONGITUDE           NUMBER(11,7)    NOT NULL,
    REASON              VARCHAR2(500),
    ACTIVE_FLAG         VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_APPLIED_AT     TIMESTAMP,
    CONSTRAINT PK_PUB_TRAVEL_COORD_H PRIMARY KEY (ID)
);

CREATE INDEX IDX_PUB_TRAVEL_COORD_EXT
    ON PUBLIC_TRAVEL_COORD_HIST (EXTERNAL_CONTENT_ID, ACTIVE_FLAG);
