CREATE SEQUENCE PUBLIC_TRAVEL_ATTRACTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PUBLIC_TRAVEL_ATTRACTION (
    ID                  NUMBER(19,0)    NOT NULL,
    EXTERNAL_CONTENT_ID VARCHAR2(50)    NOT NULL,
    TITLE               VARCHAR2(300)   NOT NULL,
    ADDRESS             VARCHAR2(500),
    IMAGE_URL           VARCHAR2(1000),
    LATITUDE            NUMBER(11,7),
    LONGITUDE           NUMBER(11,7),
    AREA_CODE           VARCHAR2(20),
    ACTIVE_FLAG         VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_SYNCED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PUB_TRAVEL_ATTR PRIMARY KEY (ID),
    CONSTRAINT UK_PUB_TRAVEL_CONTENT UNIQUE (EXTERNAL_CONTENT_ID),
    CONSTRAINT CK_PUB_TRAVEL_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N'))
);

CREATE INDEX IDX_PUBLIC_TRAVEL_AREA_ACTIVE
    ON PUBLIC_TRAVEL_ATTRACTION (AREA_CODE, ACTIVE_FLAG);

CREATE INDEX IDX_PUBLIC_TRAVEL_ACTIVE_TITLE
    ON PUBLIC_TRAVEL_ATTRACTION (ACTIVE_FLAG, TITLE);
