CREATE SEQUENCE TASK_BOARD_ITEM_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TASK_BOARD_ITEM (
    ID          NUMBER(19,0)      NOT NULL,
    USER_ID     VARCHAR2(100)     NOT NULL,
    PAGE_KEY    VARCHAR2(100)     NOT NULL,
    TASK_TEXT   VARCHAR2(200)     NOT NULL,
    STATUS      VARCHAR2(20)      NOT NULL,
    CREATED_AT  TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TASK_BOARD_ITEM PRIMARY KEY (ID),
    CONSTRAINT CK_TASK_BOARD_STATUS CHECK (STATUS IN ('todo', 'doing', 'done'))
);

CREATE INDEX IDX_TASK_BOARD_USER_PAGE
    ON TASK_BOARD_ITEM (USER_ID, PAGE_KEY, CREATED_AT);
