-- ============================================================
-- HomeHub - 국내 여행 장소 테이블 DDL (Oracle 11g XE)
-- ============================================================

-- 시퀀스
CREATE SEQUENCE TRAVEL_PLACE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 테이블
CREATE TABLE TRAVEL_PLACE (
    ID          NUMBER(19,0)    NOT NULL,
    USER_ID     VARCHAR2(100)   NOT NULL,
    CATEGORY    VARCHAR2(20)    NOT NULL,           -- TRAVEL | RESTAURANT
    PLACE_NAME  VARCHAR2(200)   NOT NULL,
    ADDRESS     VARCHAR2(500)   NOT NULL,
    REVIEW      VARCHAR2(4000),
    IMAGE_URL   VARCHAR2(500),
    LATITUDE    NUMBER(11,7),
    LONGITUDE   NUMBER(11,7),
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TRAVEL_PLACE PRIMARY KEY (ID),
    CONSTRAINT CK_TRAVEL_CATEGORY CHECK (CATEGORY IN ('TRAVEL', 'RESTAURANT'))
);

COMMENT ON TABLE TRAVEL_PLACE IS '여행지 및 맛집 방문 기록';
COMMENT ON COLUMN TRAVEL_PLACE.USER_ID IS '로그인한 사용자 아이디';
COMMENT ON COLUMN TRAVEL_PLACE.CATEGORY IS 'TRAVEL: 여행지, RESTAURANT: 맛집';
COMMENT ON COLUMN TRAVEL_PLACE.PLACE_NAME IS '저장한 장소 이름';
COMMENT ON COLUMN TRAVEL_PLACE.ADDRESS IS '선택한 주소';
COMMENT ON COLUMN TRAVEL_PLACE.REVIEW IS '후기 또는 메모';
COMMENT ON COLUMN TRAVEL_PLACE.LATITUDE IS '위도';
COMMENT ON COLUMN TRAVEL_PLACE.LONGITUDE IS '경도';
COMMENT ON COLUMN TRAVEL_PLACE.CREATED_AT IS '생성 일시';
